# Generated by Django 4.2.2 on 2023-06-27 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restuarent', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='NAME',
            new_name='Name',
        ),
    ]
